[WINDOW_STATE]
ScreenWidth= 640
ScreenHeight= 480


########################################
#  ƒQ[ƒ€ƒpƒbƒh@ƒvƒƒtƒ@ƒCƒ‹          # 
########################################

# "„§ƒfƒoƒCƒX" ELECOM  JC-U1012F—p ƒL[Ý’è

[JC-U1012F]
START = 11
SELECT = 10
CIRCLE = 3
TRIANGLE = 1
SQUARE = 0
CROSS = 2
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 8
R3 = 9

#----------------------------------------------------------------------
#ELECOM JC-U1512V—p ƒL[Ý’è

[ELECOM JC-U1512F/V series]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11

#----------------------------------------------------------------------
#ƒTƒ“ƒƒTƒvƒ‰ƒC JY-P60U —pƒL[Ý’è
[JY-P60U Series MICRO GRIP2]
START = 9
SELECT = 8
CIRCLE = 0
TRIANGLE = 2
SQUARE = 3
CROSS = 1
L1 = 4
R1 = 6
L2 = 5
R2 = 7
R3 = 11
L3 = 10

#----------------------------------------------------------------------
#ƒTƒ“ƒƒTƒvƒ‰ƒC JY-P58U —pƒL[Ý’è
[JY-P58U Series MICRO GRIP Pro]
START = 9
SELECT = 8
CIRCLE = 2
TRIANGLE = 3
SQUARE = 1
CROSS = 0
L1 = 4
R1 = 6
L2 = 5
R2 = 7
R3 = 11
L3 = 10

#----------------------------------------------------------------------
# "„§ƒfƒoƒCƒX" ELECOM  JC-UD12RD—p ƒL[Ý’è

[JC-U1012F JC-UD12RD JC-UB12GN]
START = 11
SELECT = 10
CIRCLE = 3
TRIANGLE = 1
SQUARE = 0
CROSS = 2
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 8
R3 = 9
L<->R = 0

#----------------------------------------------------------------------
[Controller (XBOX 360 Wireless Receiver for Windows)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[XBOX 360 For Windows (Controller)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[XBOX 360 Wireless Receiver for Windows(Controller)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[MadCatz GamePad (Controller)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[Controller (Afterglow Gamepad for Xbox 360)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[Controller (XBOX One For Windows)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[Controller (Controller(XBOX One For Windows))]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[Controller (XBOX 360 For Windows)]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[Controller (Controller(XBOX 360 For Windows))]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
#PS5 Controller (Wireless Mode)
[DualSense Wireless Controller]
START = 9
SELECT = 8
CIRCLE = 2
TRIANGLE = 3
SQUARE = 0
CROSS = 1
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
#PS4 Controller
[Wireless Controller]
START = 9
SELECT = 8
CIRCLE = 2
TRIANGLE = 3
SQUARE = 0
CROSS = 1
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
[DS3 Compatible HID Device]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[PLAYSTATION(R)3 Controller]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 0
SQUARE = 3
CROSS = 2
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
[Twin USB Vibration Gamepad]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 0
SQUARE = 3
CROSS = 2
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 1

#----------------------------------------------------------------------
[Bluetooth XINPUT compatible input device]
START = 7
SELECT = 6
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 10
R2 = 11
L3 = 8
R3 = 9
L<->R = 1

#----------------------------------------------------------------------
[SPEEDLINK STRIKE Gamepad]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 0
SQUARE = 3
CROSS = 2
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
#DOBE Wireless Controller For Switch TNS-0117
[Gamepad]
START = 11
SELECT = 10
CIRCLE = 1
TRIANGLE = 4
SQUARE = 3
CROSS = 0
L1 = 6
R1 = 7
L2 = 8
R2 = 9
L3 = 13
R3 = 14
L<->R = 0

#----------------------------------------------------------------------
#GameSir T4 Pro - N-Switch Controller Mode
[Pro]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
[HORI PAD 3 TURBO]
START = 9
SELECT = 8
CIRCLE = 2
TRIANGLE = 3
SQUARE = 0
CROSS = 1
L1 = 4
R1 = 5
L2 = 6
R2 = 7
L3 = 10
R3 = 11
L<->R = 0

#----------------------------------------------------------------------
[Stadia Controller rev. A]
START = 9
SELECT = 8
CIRCLE = 1
TRIANGLE = 3
SQUARE = 2
CROSS = 0
L1 = 4
R1 = 5
L2 = 12
R2 = 11
L3 = 6
R3 = 7
L<->R = 1
