Plugin = SDL2
ControllerBackend = SDL2

; NOTE: 
; - Game version 1.3.0 required
; - Move/rename/delete "dmc3se.ini" in the game folder

[Mapper]
Type = DMC3SE

[Log]
Enabled = no
Level = 4

[CustomMapper:DMC3SE]
Template = StandardGamepad

StickLeftX          = Axis(RotZ)
StickLeftY          = Axis(Z)
StickRightX         = Axis(Y)
StickRightY         = Axis(X)

ButtonA             = Button(3)
ButtonB             = Button(4)
ButtonX             = Button(1)
ButtonY             = Button(2)
ButtonLB            = Button(5)
ButtonRB            = Button(6) 
TriggerLT           = Button(7)
TriggerRT           = Button(8)
ButtonBack          = Button(11)
ButtonStart         = Button(12)
ButtonLS            = Button(9)
ButtonRS            = Button(10)